version: 1.0.{build}
environment:
  access_token:
    secure: a5T2Iw6+kjHyw+OeLIg4/ShLTnp4HDQeuLonEU50iD4xB/vu9Hpot0vWSDO24l/5
build_script:
- cmd: build.bat
on_success:
  - git config --global credential.helper store
  - git config --global push.default matching
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - cd bin
  - git push origin